POST http://localhost:3001/api/diagnoses
content-type: application/json

{
  "data": "BES"
}

###
POST http://localhost:3001/api/patients
content-type: application/json

{
  "name": "John Lucas",
  "dafeOfBirth": "2001-01-01",
  "gender": "male",
  "occupation": "How many do you need",
  "ssn": "12345-1231-NSDFA"
}
